# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Home
site_url: https://github.com/fralfaro/aves
site_author: Francisco Alfaro
site_description: "AVES: Análisis y Visualización, Educación y Soporte"

# Repository
repo_name: fralfaro/aves
repo_url: https://github.com/fralfaro/aves
edit_uri: ''


# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  logo: images/logo.bmp
  favicon: images/ave.png
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fralfaro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/faam/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/faamds
    - icon: fontawesome/brands/medium
      link: https://medium.com/@fralfaro
    - icon: fontawesome/solid/globe
      link: https://fralfaro.github.io/portfolio/

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - index.md
    - Instrucciones:
        - markdowns/rubrica-proyecto.md
        - markdowns/resources.md
        - markdowns/showcase.md
    - Unidades Teóricas:
        - markdowns/clase_01.md
        - markdowns/clase_02.md
        - markdowns/clase_03.md
        - markdowns/clase_04.md
        - markdowns/clase_05.md
        - markdowns/clase_06.md
        - markdowns/clase_07.md
        - markdowns/clase_08.md
        - markdowns/clase_09.md
        - markdowns/clase_10.md
        - markdowns/clase_11.md
    - Unidades Prácticas:
        - notebooks/vis-course/01-python-tools.ipynb
        - notebooks/vis-course/02-python-tablas.ipynb
        - notebooks/vis-course/03-python-mapas-preliminario.ipynb
        - notebooks/vis-course/03-python-mapas.ipynb
        - notebooks/vis-course/04-python-redes-preliminario.ipynb
        - notebooks/vis-course/05-python-redes-eod.ipynb
        - notebooks/vis-course/06-python-texto-guaguas.ipynb
        - notebooks/vis-course/07-python-gridspec.ipynb




